"""EyeGuard — local-only screen-content accountability monitor for macOS."""

# Run fully OFFLINE. As of 2026-09-10 the runtime no longer imports
# `transformers` at all — CLIP image preprocessing is vendored in
# clip_preprocess.py and the prompt embeddings are precomputed into
# clip_assets/text_features.npz (regenerated by the dev-only tools/). These
# env vars are kept as a belt-and-braces guard in case a future dependency
# pulls huggingface in.
import os as _os

_os.environ.setdefault("HF_HUB_OFFLINE", "1")
_os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")
_os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

__version__ = "0.3.0"   # keep in step with config.yaml's file_integrity.version
